### ISSUE TITLE
nonexistent directory "/opt/gcc/4.4.4/lib/gcc/i386-pc-solaris2.11/4.4.4/../../../../i386-pc-solaris2.11/include"

### ISSUE THREAD

**Issue by ghost** [illumos/gcc#12]
Thought I'd give this a run as a standard compiler, but after unpacking to /opt I noticed the following:

~$ /opt/gcc/4.4.4/bin/cpp -v
Using built-in specs.
Target: i386-pc-solaris2.11
Configured with: ../../configure --prefix=/opt/gcc/4.4.4 --with-as=/usr/sfw/bin/gas --with-gnu-as --with-ld=/usr/bin/ld --without-gnu-ld --enable-languages=c,c++,objc --enable-shared --with-mpfr-include=/usr/include/mpfr --with-gmp-include=/usr/include/gmp --with-pkgversion='Illumos tags/gcc-4.4.4-il-2' --with-bugurl=http://github.com/richlowe/gcc/issues
Thread model: posix
gcc version 4.4.4 (Illumos tags/gcc-4.4.4-il-2) 
COLLECT_GCC_OPTIONS='-E' '-v' '-mtune=i386'
 /opt/gcc/4.4.4/libexec/gcc/i386-pc-solaris2.11/4.4.4/cc1 -E -quiet -v - -mtune=i386
ignoring nonexistent directory "/opt/gcc/4.4.4/lib/gcc/i386-pc-solaris2.11/4.4.4/../../../../i386-pc-solaris2.11/include"
# include "..." search starts here:
# include <...> search starts here:

 /usr/local/include
 /opt/gcc/4.4.4/include
 /opt/gcc/4.4.4/lib/gcc/i386-pc-solaris2.11/4.4.4/include
 /opt/gcc/4.4.4/lib/gcc/i386-pc-solaris2.11/4.4.4/include-fixed
 /usr/include
End of search list.
^C

Did I do something wrong?

**Comment by ghost** [comment]
Since this is preprocessor, here's output with null input:

```
~$ /opt/gcc/4.4.4/bin/cpp -v /dev/null
Using built-in specs.
Target: i386-pc-solaris2.11
Configured with: ../../configure --prefix=/opt/gcc/4.4.4 --with-as=/usr/sfw/bin/gas --with-gnu-as --with-ld=/usr/bin/ld --without-gnu-ld --enable-languages=c,c++,objc --enable-shared --with-mpfr-include=/usr/include/mpfr --with-gmp-include=/usr/include/gmp --with-pkgversion='Illumos tags/gcc-4.4.4-il-2' --with-bugurl=http://github.com/richlowe/gcc/issues
Thread model: posix
gcc version 4.4.4 (Illumos tags/gcc-4.4.4-il-2) 
COLLECT_GCC_OPTIONS='-E' '-v' '-mtune=i386'
 /opt/gcc/4.4.4/libexec/gcc/i386-pc-solaris2.11/4.4.4/cc1 -E -quiet -v /dev/null -mtune=i386
ignoring nonexistent directory "/opt/gcc/4.4.4/lib/gcc/i386-pc-solaris2.11/4.4.4/../../../../i386-pc-solaris2.11/include"
#include "..." search starts here:
#include <...> search starts here:
 /usr/local/include
 /opt/gcc/4.4.4/include
 /opt/gcc/4.4.4/lib/gcc/i386-pc-solaris2.11/4.4.4/include
 /opt/gcc/4.4.4/lib/gcc/i386-pc-solaris2.11/4.4.4/include-fixed
 /usr/include
End of search list.
# 1 "/dev/null"
# 1 "<built-in>"
# 1 "<command-line>"
# 1 "/dev/null"
COMPILER_PATH=/opt/gcc/4.4.4/libexec/gcc/i386-pc-solaris2.11/4.4.4/:/opt/gcc/4.4.4/libexec/gcc/i386-pc-solaris2.11/4.4.4/:/opt/gcc/4.4.4/libexec/gcc/i386-pc-solaris2.11/:/opt/gcc/4.4.4/lib/gcc/i386-pc-solaris2.11/4.4.4/:/opt/gcc/4.4.4/lib/gcc/i386-pc-solaris2.11/:/usr/ccs/bin/
LIBRARY_PATH=/opt/gcc/4.4.4/lib/gcc/i386-pc-solaris2.11/4.4.4/:/opt/gcc/4.4.4/lib/gcc/i386-pc-solaris2.11/4.4.4/../../../:/lib/:/usr/lib/
COLLECT_GCC_OPTIONS='-E' '-v' '-mtune=i386'
```

**Comment by richlowe** [comment]
Its possible I somehow screwed up the tarball, but I can't check until tomorrow.   Does it it actually work?  All I see in the report is the missing directory message.   

The tarballs are of the installed copy I'm actually using, so I would hope it worked fine...

**Comment by richlowe** [comment]
This is completely normal
