### ISSUE TITLE
initial 9.1 work

### ISSUE THREAD

**Issue by richlowe** [illumos/gcc#24]
Initial work for 9.1.0 is here:
   https://github.com/illumos/gcc/compare/3defceaa1a29...richlowe:il-9_1_0?expand=1

I'd like to bring this into illumos/gcc, following IPD 7's path of putting works-in-progress in illumos/gcc.

This is a straight rebase of the 8.3 branch, with changes fixed upstream (mapfile v2) dropped, and a place holder disabling libsanitizer until we fix it.

Test changes look like:

```
Tests that now fail, but worked before:

unix//-m64: gcc.target/i386/pr57193.c scan-assembler-times movdqa 2
unix/: gcc.target/i386/pr57193.c scan-assembler-times movdqa 2
unix/: gcc.target/i386/pr81563.c scan-assembler-times movl[\\t ]*-4\\(%ebp\\),[\\t ]*%edi 1
unix/: gcc.target/i386/pr81563.c scan-assembler-times movl[\\t ]*-8\\(%ebp\\),[\\t ]*%esi 1

New tests that FAIL:

unix//-m64: g++.dg/lto/pr89335 cp_lto_pr89335_0.o assemble, -O2 -flto -Wsuggest-final-methods
unix//-m64: g++.dg/pr80481.C  -std=gnu++17  scan-assembler-not vmovaps
unix//-m64: gcc.dg/ipa/ipa-icf-38.c scan-ltrans-tree-dump-not optimized "Function bar"
unix//-m64: gcc.target/i386/ipa-stack-alignment-2.c scan-assembler sub.*%.sp
unix//-m64: gcc.target/i386/ipa-stack-alignment.c scan-assembler sub.*%.sp
unix//-m64: gcc.target/i386/pr34256.c scan-assembler-times mov 3
unix//-m64: gcc.target/i386/pr90178.c scan-assembler-times xorl[\\t ]*\\%eax,[\\t ]*%eax 1
unix//-m64: gcc.target/i386/vartrack-1.c scan-rtl-dump-times vartrack "[0-9][0-9]*: {\\[argp:DI-0x10\\]=bx:DI;sp:DI=argp:DI-0x10;}" 1
unix//-m64: gcc.target/i386/vartrack-1.c scan-rtl-dump-times vartrack "[0-9][0-9]*: {bx:DI=\\[argp:DI-0x10\\];sp:DI=argp:DI-0x8;}" 1
unix/: g++.dg/lto/pr89335 cp_lto_pr89335_0.o assemble, -O2 -flto -Wsuggest-final-methods
unix/: gcc.dg/ipa/ipa-icf-38.c scan-ltrans-tree-dump-not optimized "Function bar"
unix/: gcc.target/i386/pr18041-2.c scan-assembler-times and 1
unix/: gcc.target/i386/pr18041-2.c scan-assembler-times or 1
unix/: gcc.target/i386/pr89676.c scan-assembler-times movl 2
unix/: gcc.target/i386/pr90178.c scan-assembler-times xorl[\\t ]*\\%eax,[\\t ]*%eax 1
```

@jclulow @jlevon @citrus-it @alarcher

**Comment by richlowe** [comment]
(This is an issue, not a pull request, because as @citrus-it has pointed out in the past.  Bloody github doesn't let you create a pull request except to a branch which already exists.)

**Comment by alarcher** [comment]
Thanks :) The libsanitizer was the work in progress I mentioned some time ago.

**Comment by richlowe** [comment]
Was anyone going to review this for me? or state an opinion?

**Comment by jclulow** [comment]
I have not looked super closely at the actual patches but the fact that you've been able to get tests to run and such bodes very well.  It seems fine to push this to the expect branch, as per IPD 7, and we'll start whittling towards a tag that people can ship?

**Comment by richlowe** [comment]
Precisely the plan!  I'll get this done.  Thanks.
