### ISSUE TITLE
Building an illumos gcc 9.2.0

### ISSUE THREAD

**Issue by citrus-it** [illumos/gcc#34]
Hi,

I'd like to start work on an illumos gcc 9.2.0 branch, ready for when the gcc8/9 cleanup work is at the point where we want to start running gcc9 as a shadow, and to make sure that that same cleanup work is being done under a compiler with the right values stuff.

To that end, please could somebody create a new `il-9_2_0` branch based on upstream's `gcc-9_2_0-release` tag, and then I can raise some PRs against it to rebase Rich's work from the il-9_1_0 branch, and to add some more commits that we have in the OOCE branch.

Thanks

@richlowe @jclulow

**Comment by richlowe** [comment]
This should be there in a minute or two, based on the `releases/gcc-9.2.0` tag

**Comment by citrus-it** [comment]
Not seeing it yet.

**Comment by richlowe** [comment]
I tried to just create the branch from the tag, and git outsmarted me and decided to create a new tag instead.  It should be done properly now?
