### ISSUE TITLE
Could let #pragma align() work the normal way

### ISSUE THREAD

**Issue by richlowe** [illumos/gcc#9]
We patch `#pragma align` such that it may be applied to variables following their definition.  Something which GCC would normally disallow.

It is just as tractable for us to fix our code to stop trying to align things after their definition, and to then drop the patch.

**Comment by richlowe** [comment]
The illumos side of this is [#2732 consistent use of #pragma align would please GCC](http://illumos.org/issues/2732)

**Comment by rmustacc** [comment]
@richlowe since we now have this in place should we look at dropping a patch here?

**Comment by richlowe** [comment]
Yes.  it's also possible we already did and this wasn't closed.

**Comment by richlowe** [comment]
yes, it seems we already removed this patch
